server:
  port: 7010
spring:
  application:
    name: images


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


accessKey: Y9mOOnlwXSocxJtntYqQIR6k7Dwf_n3Icsn5Ep8e    #访问秘钥
secretKey: 6GQLTIErXis_YicJ3h7gHBp1OGqoawQpRk7ZKikB    #授权秘钥
bucket: cxp                                            #存储空间名称
domain: http://q72z15qf5.bkt.clouddn.com/              #外链域名

