server:
  port: 7060
spring:
  application:
    name: car
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cxpshop
    username: root
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cxp.shop_api.entity
  configuration:
    map-underscore-to-camel-case: true


### Hystrix 配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 熔断器超时时间，默认：1000/毫秒
            timeoutInMilliseconds: 5000
